canonical_bases:
  - original: "python:3.11-slim"
    suggested: "Use the Cisco's internal chainguard base image python:3.11-slim"
  - original: "node:20-alpine"
    suggested: "Use the Cisco's internal chainguard base image node:20-alpine"