name: Smart Image Consolidator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install anchorecli  # <-- installs anchore-cli

      - name: Verify Anchore CLI
        run: anchore-cli --version

      - name: Run Smart Image Consolidator
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}